# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userinterface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcome(object):
    def setupUi(self, welcome):
        welcome.setObjectName("welcome")
        welcome.setWindowModality(QtCore.Qt.NonModal)
        welcome.setEnabled(True)
        welcome.resize(1306, 906)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(welcome.sizePolicy().hasHeightForWidth())
        welcome.setSizePolicy(sizePolicy)
        welcome.setMinimumSize(QtCore.QSize(1306, 906))
        welcome.setMaximumSize(QtCore.QSize(1306, 906))
        welcome.setMouseTracking(True)
        welcome.setFocusPolicy(QtCore.Qt.StrongFocus)
        welcome.setToolTip("")
        welcome.setStyleSheet(" background-image: url(C:/Users/abdijavad110/Documents/UNI/97-98 1/Data Base/project/ui/welcome_background.jpg);\n"
" background-repeat: norepeat;")
        welcome.setAnimated(True)
        welcome.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(welcome)
        self.centralwidget.setObjectName("centralwidget")
        self.src_ico = QtWidgets.QLabel(self.centralwidget)
        self.src_ico.setEnabled(True)
        self.src_ico.setGeometry(QtCore.QRect(90, 90, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.src_ico.sizePolicy().hasHeightForWidth())
        self.src_ico.setSizePolicy(sizePolicy)
        self.src_ico.setMaximumSize(QtCore.QSize(200, 200))
        self.src_ico.setStyleSheet("background: transparent;")
        self.src_ico.setText("")
        self.src_ico.setPixmap(QtGui.QPixmap("ui/source.png"))
        self.src_ico.setScaledContents(True)
        self.src_ico.setObjectName("src_ico")
        self.des_ico = QtWidgets.QLabel(self.centralwidget)
        self.des_ico.setEnabled(True)
        self.des_ico.setGeometry(QtCore.QRect(90, 200, 90, 90))
        self.des_ico.setStyleSheet("background: transparent;")
        self.des_ico.setText("")
        self.des_ico.setPixmap(QtGui.QPixmap("ui/destination.png"))
        self.des_ico.setScaledContents(True)
        self.des_ico.setObjectName("des_ico")
        self.src_x = QtWidgets.QLineEdit(self.centralwidget)
        self.src_x.setGeometry(QtCore.QRect(200, 95, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.src_x.setFont(font)
        self.src_x.setStyleSheet("background: transparent;\n")
        self.src_x.setText("")
        self.src_x.setObjectName("src_x")
        self.des_x = QtWidgets.QLineEdit(self.centralwidget)
        self.des_x.setGeometry(QtCore.QRect(200, 205, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.des_x.setFont(font)
        self.des_x.setStyleSheet("background: transparent;\n")
        self.des_x.setText("")
        self.des_x.setObjectName("des_x")
        self.src_y = QtWidgets.QLineEdit(self.centralwidget)
        self.src_y.setGeometry(QtCore.QRect(410, 95, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.src_y.setFont(font)
        self.src_y.setStyleSheet("background: transparent;\n")
        self.src_y.setText("")
        self.src_y.setObjectName("src_y")
        self.des_y = QtWidgets.QLineEdit(self.centralwidget)
        self.des_y.setGeometry(QtCore.QRect(410, 205, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.des_y.setFont(font)
        self.des_y.setStyleSheet("background: transparent;\n")
        self.des_y.setText("")
        self.des_y.setObjectName("des_y")
        self.req_car_womens = QtWidgets.QLabel(self.centralwidget)
        self.req_car_womens.setEnabled(True)
        self.req_car_womens.setGeometry(QtCore.QRect(390, 350, 90, 80))
        self.req_car_womens.setStyleSheet("background: transparent;")
        self.req_car_womens.setText("")
        self.req_car_womens.setPixmap(QtGui.QPixmap("ui/car_purple.png"))
        self.req_car_womens.setScaledContents(True)
        self.req_car_womens.setObjectName("req_car_womens")
        self.req_car_eco = QtWidgets.QLabel(self.centralwidget)
        self.req_car_eco.setEnabled(True)
        self.req_car_eco.setGeometry(QtCore.QRect(150, 350, 90, 80))
        self.req_car_eco.setMouseTracking(False)
        self.req_car_eco.setStyleSheet("background: transparent;")
        self.req_car_eco.setText("")
        self.req_car_eco.setPixmap(QtGui.QPixmap("ui/car_eco.png"))
        self.req_car_eco.setScaledContents(True)
        self.req_car_eco.setObjectName("req_car_eco")
        self.req_car_luxury = QtWidgets.QLabel(self.centralwidget)
        self.req_car_luxury.setEnabled(True)
        self.req_car_luxury.setGeometry(QtCore.QRect(270, 325, 90, 120))
        self.req_car_luxury.setStyleSheet("background: transparent;")
        self.req_car_luxury.setText("")
        self.req_car_luxury.setPixmap(QtGui.QPixmap("ui/car_luxury.png"))
        self.req_car_luxury.setScaledContents(True)
        self.req_car_luxury.setObjectName("req_car_luxury")
        self.req_car_motor = QtWidgets.QLabel(self.centralwidget)
        self.req_car_motor.setEnabled(True)
        self.req_car_motor.setGeometry(QtCore.QRect(510, 348, 80, 80))
        self.req_car_motor.setStyleSheet("background: transparent;")
        self.req_car_motor.setText("")
        self.req_car_motor.setPixmap(QtGui.QPixmap("ui/car_motorcycle.png"))
        self.req_car_motor.setScaledContents(True)
        self.req_car_motor.setObjectName("req_car_motor")
        welcome.setCentralWidget(self.centralwidget)

        self.retranslateUi(welcome)
        QtCore.QMetaObject.connectSlotsByName(welcome)

        #self.req_car_eco.clicked.connect(self.req_car_eco)

    def retranslateUi(self, welcome):
        _translate = QtCore.QCoreApplication.translate
        welcome.setWindowTitle(_translate("welcome", "welcome"))

    def req_car_eco(self):
        print("eco")
