# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!
import threading

from PyQt5 import QtCore, QtGui, QtWidgets
from math import sqrt
from passenger_client import passenger_client
priceRate = 1
driver = None
passenger = '09031479910'

class Ui_mainWidow(object):
    def setupUi(self, mainWidow):
        # main
        mainWidow.setObjectName("mainWidow")
        mainWidow.setWindowModality(QtCore.Qt.NonModal)
        mainWidow.setEnabled(True)
        mainWidow.resize(1306, 906)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWidow.sizePolicy().hasHeightForWidth())
        mainWidow.setSizePolicy(sizePolicy)
        mainWidow.setMinimumSize(QtCore.QSize(1306, 906))
        mainWidow.setMaximumSize(QtCore.QSize(1306, 906))
        mainWidow.setMouseTracking(True)
        mainWidow.setFocusPolicy(QtCore.Qt.StrongFocus)
        mainWidow.setToolTip("")
        mainWidow.setStyleSheet(" background-image: url(C:/Users/abdijavad110/Documents/UNI/97-98 1/Data Base/project/ui/welcome_background.jpg);\n"
" background-repeat: norepeat;")
        mainWidow.setAnimated(True)
        mainWidow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(mainWidow)
        self.centralwidget.setObjectName("centralwidget")
        # src_and_des_ico
        self.src_ico = QtWidgets.QLabel(self.centralwidget)
        self.src_ico.setEnabled(True)
        self.src_ico.setGeometry(QtCore.QRect(90, 90, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.src_ico.sizePolicy().hasHeightForWidth())
        self.src_ico.setSizePolicy(sizePolicy)
        self.src_ico.setMaximumSize(QtCore.QSize(200, 200))
        self.src_ico.setStyleSheet("background: transparent;")
        self.src_ico.setText("")
        self.src_ico.setPixmap(QtGui.QPixmap("ui/source.png"))
        self.src_ico.setScaledContents(True)
        self.src_ico.setObjectName("src_ico")
        self.des_ico = QtWidgets.QLabel(self.centralwidget)
        self.des_ico.setEnabled(True)
        self.des_ico.setGeometry(QtCore.QRect(90, 200, 90, 90))
        self.des_ico.setStyleSheet("background: transparent;")
        self.des_ico.setText("")
        self.des_ico.setPixmap(QtGui.QPixmap("ui/destination.png"))
        self.des_ico.setScaledContents(True)
        self.des_ico.setObjectName("des_ico")
        # src_x_y_and_des_x_y
        self.src_x = QtWidgets.QLineEdit(self.centralwidget)
        self.src_x.setGeometry(QtCore.QRect(200, 95, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.src_x.setFont(font)
        self.src_x.setStyleSheet("background: transparent;\n"
"mouse-over-background-color: yellow;")
        self.src_x.setText("0")
        self.src_x.setObjectName("src_x")
        self.des_x = QtWidgets.QLineEdit(self.centralwidget)
        self.des_x.setGeometry(QtCore.QRect(200, 205, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.des_x.setFont(font)
        self.des_x.setStyleSheet("background: transparent;\n"
"mouse-over-background-color: yellow;")
        self.des_x.setText("0")
        self.des_x.setObjectName("des_x")
        self.src_y = QtWidgets.QLineEdit(self.centralwidget)
        self.src_y.setGeometry(QtCore.QRect(410, 95, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.src_y.setFont(font)
        self.src_y.setStyleSheet("background: transparent;\n"
"mouse-over-background-color: yellow;")
        self.src_y.setText("0")
        self.src_y.setObjectName("src_y")
        self.des_y = QtWidgets.QLineEdit(self.centralwidget)
        self.des_y.setGeometry(QtCore.QRect(410, 205, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.des_y.setFont(font)
        self.des_y.setStyleSheet("background: transparent;\n"
"mouse-over-background-color: yellow;")
        self.des_y.setText("0")
        self.des_y.setObjectName("des_y")
        self.src_x.setValidator(QtGui.QDoubleValidator())
        self.src_y.setValidator(QtGui.QDoubleValidator())
        self.des_x.setValidator(QtGui.QDoubleValidator())
        self.des_x.setValidator(QtGui.QDoubleValidator())

        # cost
        self.price = QtWidgets.QLabel(self.centralwidget)
        self.price.setEnabled(True)
        self.price.setGeometry(QtCore.QRect(290, 290, 290, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.src_ico.sizePolicy().hasHeightForWidth())
        self.price.setSizePolicy(sizePolicy)
        self.price.setMaximumSize(QtCore.QSize(200, 200))
        self.price.setStyleSheet("background: transparent;")
        self.price.setText("price: 0")
        self.price.setObjectName("src_ico")
        # car_requests_ico
        self.req_car_womens_ico = QtWidgets.QLabel(self.centralwidget)
        self.req_car_womens_ico.setEnabled(True)
        self.req_car_womens_ico.setGeometry(QtCore.QRect(390, 350, 90, 80))
        self.req_car_womens_ico.setStyleSheet("background: transparent;")
        self.req_car_womens_ico.setText("")
        self.req_car_womens_ico.setPixmap(QtGui.QPixmap("ui/car_purple.png"))
        self.req_car_womens_ico.setScaledContents(True)
        self.req_car_womens_ico.setObjectName("req_car_womens_ico")
        self.req_car_eco_ico = QtWidgets.QLabel(self.centralwidget)
        self.req_car_eco_ico.setEnabled(True)
        self.req_car_eco_ico.setGeometry(QtCore.QRect(150, 350, 90, 80))
        self.req_car_eco_ico.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.req_car_eco_ico.setMouseTracking(False)
        self.req_car_eco_ico.setStyleSheet("background: transparent;")
        self.req_car_eco_ico.setText("")
        self.req_car_eco_ico.setPixmap(QtGui.QPixmap("ui/car_eco.png"))
        self.req_car_eco_ico.setScaledContents(True)
        self.req_car_eco_ico.setObjectName("req_car_eco_ico")
        self.req_car_luxury_ico = QtWidgets.QLabel(self.centralwidget)
        self.req_car_luxury_ico.setEnabled(True)
        self.req_car_luxury_ico.setGeometry(QtCore.QRect(270, 325, 90, 120))
        self.req_car_luxury_ico.setStyleSheet("background: transparent;")
        self.req_car_luxury_ico.setText("")
        self.req_car_luxury_ico.setPixmap(QtGui.QPixmap("ui/car_luxury.png"))
        self.req_car_luxury_ico.setScaledContents(True)
        self.req_car_luxury_ico.setObjectName("req_car_luxury_ico")
        self.req_car_motor_ico = QtWidgets.QLabel(self.centralwidget)
        self.req_car_motor_ico.setEnabled(True)
        self.req_car_motor_ico.setGeometry(QtCore.QRect(510, 348, 80, 80))
        self.req_car_motor_ico.setStyleSheet("background: transparent;")
        self.req_car_motor_ico.setText("")
        self.req_car_motor_ico.setPixmap(QtGui.QPixmap("ui/car_motorcycle.png"))
        self.req_car_motor_ico.setScaledContents(True)
        self.req_car_motor_ico.setObjectName("req_car_motor_ico")
        # car_requests_btn
        self.req_car_luxury = QtWidgets.QPushButton(self.centralwidget)
        self.req_car_luxury.setGeometry(QtCore.QRect(270, 350, 91, 81))
        self.req_car_luxury.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.req_car_luxury.setAutoFillBackground(False)
        self.req_car_luxury.setStyleSheet("background:transparent;")
        self.req_car_luxury.setText("")
        self.req_car_luxury.setObjectName("req_car_luxury")
        self.req_car_woman = QtWidgets.QPushButton(self.centralwidget)
        self.req_car_woman.setGeometry(QtCore.QRect(390, 350, 91, 81))
        self.req_car_woman.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.req_car_woman.setAutoFillBackground(False)
        self.req_car_woman.setStyleSheet("background:transparent;")
        self.req_car_woman.setText("")
        self.req_car_woman.setObjectName("req_car_woman")
        self.req_car_motorcycle = QtWidgets.QPushButton(self.centralwidget)
        self.req_car_motorcycle.setGeometry(QtCore.QRect(510, 350, 91, 81))
        self.req_car_motorcycle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.req_car_motorcycle.setAutoFillBackground(False)
        self.req_car_motorcycle.setStyleSheet("background:transparent;")
        self.req_car_motorcycle.setText("")
        self.req_car_motorcycle.setObjectName("req_car_motorcycle")
        self.req_car_eco = QtWidgets.QPushButton(self.centralwidget)
        self.req_car_eco.setGeometry(QtCore.QRect(150, 350, 91, 81))
        self.req_car_eco.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.req_car_eco.setAutoFillBackground(False)
        self.req_car_eco.setStyleSheet("background:transparent;")
        self.req_car_eco.setText("")
        self.req_car_eco.setIconSize(QtCore.QSize(90, 90))
        self.req_car_eco.setAutoRepeat(False)
        self.req_car_eco.setObjectName("req_car_eco")
        # option_btn
        self.options_btn = QtWidgets.QPushButton(self.centralwidget)
        self.options_btn.setGeometry(QtCore.QRect(1100, 800, 91, 91))
        self.options_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.options_btn.setAutoFillBackground(False)
        self.options_btn.setStyleSheet("background:transparent;")
        self.options_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/options.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.options_btn.setIcon(icon)
        self.options_btn.setIconSize(QtCore.QSize(90, 90))
        self.options_btn.setAutoRepeat(False)
        self.options_btn.setObjectName("options_btn")
        # settings_btn
        self.settings_btn = QtWidgets.QPushButton(self.centralwidget)
        self.settings_btn.setGeometry(QtCore.QRect(1200, 800, 91, 91))
        self.settings_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_btn.setAutoFillBackground(False)
        self.settings_btn.setStyleSheet("background:transparent;")
        self.settings_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_btn.setIcon(icon1)
        self.settings_btn.setIconSize(QtCore.QSize(90, 90))
        self.settings_btn.setAutoRepeat(False)
        self.settings_btn.setObjectName("settings_btn")

        # back_btn
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(1000, 800, 91, 91))
        self.back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn.setAutoFillBackground(False)
        self.back_btn.setStyleSheet("background:transparent;")
        self.back_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon2)
        self.back_btn.setIconSize(QtCore.QSize(90, 90))
        self.back_btn.setAutoRepeat(False)
        self.back_btn.setObjectName("back_btn")
        # blur_bg_and_blur_bg_2
        self.blur_bg = QtWidgets.QLabel(self.centralwidget)
        self.blur_bg.setGeometry(QtCore.QRect(0, 0, 1311, 911))
        self.blur_bg.setStyleSheet("background: rgba(200, 200, 200, 200);")
        self.blur_bg.setText("")
        self.blur_bg.setObjectName("blur_bg")
        self.blur_bg.hide()
        self.blur_bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.blur_bg_2.setGeometry(QtCore.QRect(830, 0, 481, 901))
        self.blur_bg_2.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(210, 210, 200, 200), stop:1 rgba(40, 30, 5, 200))")
        self.blur_bg_2.setText("")
        self.blur_bg_2.setObjectName("blur_bg_2")
        self.blur_bg_2.hide()
        # options_layout
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(850, 30, 431, 731))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.options = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.options.setContentsMargins(10, 10, 10, 0)
        self.options.setObjectName("options")
        # option1
        self.option_label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.option_label1.setStyleSheet("background: transparent")
        self.option_label1.setObjectName("option_label1")
        self.options.addWidget(self.option_label1)
        self.option1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.option1.setFont(font)
        self.option1.setStyleSheet("background: transparent;\n"
"mouse-over-background-color: yellow;")
        self.option1.setText("")
        self.option1.hide()
        self.option_label1.hide()
        self.option1.setObjectName("option1")
        # option2
        self.options.addWidget(self.option1)
        self.option2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.option2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.option2.setStyleSheet("background: transparent")
        self.option2.setObjectName("option2")
        self.options.addWidget(self.option2)
        self.option2.hide()

        # spacer
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.options.addItem(spacerItem)
        # settings_layout
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(850, 30, 431, 731))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.settings = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.settings.setContentsMargins(10, 10, 10, 0)
        self.settings.setObjectName("settings")
        # setting1
        self.setting_label1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.setting_label1.setStyleSheet("background: transparent")
        self.setting_label1.setObjectName("setting_label1")
        self.settings.addWidget(self.setting_label1)
        self.setting1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.setting1.setFont(font)
        self.setting1.setStyleSheet("background: transparent;\n"
"mouse-over-background-color: yellow;")
        self.setting1.setText("")
        self.setting1.setObjectName("setting1")
        self.setting1.hide()
        self.setting_label1.hide()
        self.settings.addWidget(self.setting1)

        # setting2
        self.setting2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.setting2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.setting2.setStyleSheet("background: transparent")
        self.setting2.setObjectName("setting2")
        self.setting2.hide()
        self.settings.addWidget(self.setting2)
        # spacer
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settings.addItem(spacerItem1)
        # back_and_fronts
        self.req_car_motor_ico.raise_()
        self.req_car_womens_ico.raise_()
        self.req_car_eco_ico.raise_()
        self.req_car_luxury_ico.raise_()
        self.des_x.raise_()
        self.des_y.raise_()
        self.req_car_woman.raise_()
        self.des_ico.raise_()
        self.src_y.raise_()
        self.src_x.raise_()
        self.req_car_luxury.raise_()
        self.req_car_eco.raise_()
        self.req_car_motorcycle.raise_()
        self.src_ico.raise_()
        self.blur_bg.raise_()
        self.blur_bg_2.raise_()
        self.options_btn.raise_()
        self.settings_btn.raise_()
        self.back_btn.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        # find_driver_ico_and_cancel
        self.drv_find_gif = QtWidgets.QLabel(self.centralwidget)
        self.drv_find_gif.setEnabled(True)
        self.drv_find_gif.setGeometry(QtCore.QRect(500, 200, 300, 300))
        self.drv_find_gif.setMouseTracking(False)
        self.drv_find_gif.setStyleSheet("background: transparent;")
        self.drv_find_gif.setText("")
        movie = QtGui.QMovie("ui/waiting_for_driver.gif")
        self.drv_find_gif.setMovie(movie)
        movie.start()
        self.drv_find_gif.setScaledContents(True)
        self.drv_find_gif.setObjectName("finding_driver")
        self.drv_find_gif.hide()
        self.cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_btn.setGeometry(QtCore.QRect(600, 600, 100, 100))
        self.cancel_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_btn.setAutoFillBackground(False)
        self.cancel_btn.setStyleSheet("background:transparent;")
        self.cancel_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_btn.setIcon(icon3)
        self.cancel_btn.setIconSize(QtCore.QSize(100, 100))
        self.cancel_btn.setAutoRepeat(False)
        self.cancel_btn.setObjectName("back_btn")
        self.cancel_btn.hide()
        self.centralwidget.setStyleSheet("background: transparent;")
        # connections
        self.back_btn.clicked.connect(self.back_clicked)
        self.options_btn.clicked.connect(self.options_clicked)
        self.settings_btn.clicked.connect(self.settings_clicked)
        self.req_car_eco.clicked.connect(self.eco_clicked)
        self.req_car_luxury.clicked.connect(self.lux_clicked)
        self.req_car_woman.clicked.connect(self.woman_clicked)
        self.req_car_motorcycle.clicked.connect(self.motor_clicked)
        self.cancel_btn.clicked.connect(self.cancel_clicked)
        self.src_x.textChanged.connect(self.update_price)
        self.src_y.textChanged.connect(self.update_price)
        self.des_x.textChanged.connect(self.update_price)
        self.des_y.textChanged.connect(self.update_price)


        mainWidow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWidow)
        QtCore.QMetaObject.connectSlotsByName(mainWidow)

    def retranslateUi(self, mainWidow):
        _translate = QtCore.QCoreApplication.translate
        mainWidow.setWindowTitle(_translate("mainWidow", "mainWindow"))
        self.option_label1.setText(_translate("mainWidow", "option_label"))
        self.option2.setText(_translate("mainWidow", "RadioButton"))
        self.setting_label1.setText(_translate("mainWidow", "setting_label"))
        self.setting2.setText(_translate("mainWidow", "RadioButton"))

    def settings_clicked(self):
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(850, 30, 431, 731))
        self.back_clicked()
        self.blur_bg.show()
        self.blur_bg_2.show()
        self.setting1.show()
        self.setting_label1.show()
        self.setting2.show()

    def options_clicked(self):
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 431, 731))
        self.back_clicked()
        self.blur_bg.show()
        self.blur_bg_2.show()
        self.option1.show()
        self.option_label1.show()
        self.option2.show()

    def back_clicked(self):
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(850, 30, 431, 731))
        self.blur_bg.hide()
        self.blur_bg_2.hide()
        self.option1.hide()
        self.option_label1.hide()
        self.option2.hide()
        self.setting1.hide()
        self.setting_label1.hide()
        self.setting2.hide()

    def motor_clicked(self):
        self.blur_bg.show()
        self.cancel_btn.show()
        self.options_btn.hide()
        self.settings_btn.hide()
        self.back_btn.hide()
        self.drv_find_gif.show()

    def eco_clicked(self):
        self.blur_bg.show()
        self.cancel_btn.show()
        self.options_btn.hide()
        self.settings_btn.hide()
        self.back_btn.hide()
        self.drv_find_gif.show()
        conn = passenger_client()
        conn.test(self.src_x.text(), self.src_y.text(), self.des_x.text(), self.des_y.text(), self.price.text(), passenger)


    def woman_clicked(self):
        self.blur_bg.show()
        self.cancel_btn.show()
        self.options_btn.hide()
        self.settings_btn.hide()
        self.back_btn.hide()
        self.drv_find_gif.show()

    def lux_clicked(self):
        self.blur_bg.show()
        self.cancel_btn.show()
        self.options_btn.hide()
        self.settings_btn.hide()
        self.back_btn.hide()
        self.drv_find_gif.show()

    def cancel_clicked(self):
        self.blur_bg.hide()
        self.cancel_btn.hide()
        self.drv_find_gif.hide()
        self.options_btn.show()
        self.settings_btn.show()
        self.back_btn.show()

    def update_price(self):
        try:
            price = sqrt((float(self.des_x.text()) - float(self.src_x.text())) ** 2 +
                        (float(self.des_y.text()) - float(self.src_y.text())) ** 2)
        except:
            price = 0
        finally:
            self.price.setText("price: " + str(int(price*priceRate*100)/100))
